Hope you're good
dylanaraps/dylanaraps pull request #1
Opened 2024-03-04 05:57 UTC by a-schaefers

2024-04-22 07:49 UTC, jumps-are-op commented
It's very close to be a year. We hope you're in the best state… *coding POSIX® shell scripts*. :)

2024-04-26 14:37 UTC, a-schaefers commented
:farmer:

2024-05-04 09:55 UTC, sukalaper commented
Hope you're good(2).

2024-07-21 06:14 UTC, kzwkt commented
Your decision to leave behind the tech world and live independently off-grid is truly commendable. By stepping away from conventional comforts and embracing self-sufficiency, you’re making a powerful statement against the capitalist norms that prioritize consumerism and dependency. It’s inspiring to see someone who not only contributes to the open-source community with KISS Linux, neofetch etc but also takes their principles to heart by living in harmony with nature and sustaining themselves independently. Your dedication to self-reliance and alternative ways of living is a remarkable example of how one can align their actions with their values. Keep blazing that trail—you’re a true pioneer!

2025-08-03 13:54 UTC, larrasket commented
@a-schaefers Please resolve conflicts

2025-08-15 15:14 UTC, a-schaefers commented
@larrasket conflicts resolved.

2025-11-11 21:44 UTC, Butterroach commented
conflicts :pensive:

2026-01-06 17:23 UTC, larrasket requested changes
@a-schaefers Please resolve conflicts

2026-02-19 22:53 UTC, a-schaefers commented
It is apparent that @dylanaraps is indeed, "good." Closing as this issue is now "resolved" per latest updates,

>  https://wild.gr/ & https://dylan.gr/1768295794

:fire:

2026-02-19 22:53 UTC, closed without merging